export { default as About } from './About/About'
export { default as Catalog } from './Catalog/Catalog'
export { default as Contact } from './Contact/Contact'
export { default as Faqs } from './Faqs/Faqs'
export { default as Home } from './Home/Home'
export { default as Work } from './Work/Work'
export { default as Testimonials } from './Testimonials/Testimonials'
export { default as Navbar } from './Navbar/Navbar'